### ISSUE TITLE
C

### ISSUE THREAD

**Issue by shulamit2000** [santec-corporation/TSL_USB_Control_Scripts#1]
Hello,

I´m using the following python code to connect to TSL-570 via USB. It seems like it´s connetced but I do not receive any query results. The TSL.Query("*IDN?") returns an empty string.

import time
import clr
import sys

assembly_path = r".\DLL"                                                #dll path
sys.path.append(assembly_path)
ref = clr.AddReference(r"Santec_FTDI")

from Santec_FTDI import FTD2xx_helper
TSL.CloseUsbConnection()

TSL = FTD2xx_helper("22101017")
raw = []
print(TSL.lastConnectedSerialNumber)
print(TSL.Query("*IDN?"))

**Comment by Chentir-MT** [comment]
Hi,
Apologies for the delay of this response.

First, I am concerned about the line:
TSL.CloseUsbConnection()

It looks you have used the TSL object before defining it.... but I trust this is a mistyping.

Now I have 2 questions:
1- Have you installed the USB driver? ([link](https://downloads.santec.com/files/downloadfile/6dbd36cd-a29e-4ca0-a894-8ba4e4fdf0c5)) <-- If you have issues on how to install this driver please let us know
2- What is the decimal separator of your OS? is it a dot or a comma?

**Comment by rpj17-santec** [comment]
Hi there, 

Hoping that your issue is solved, shall I close this issue with 'RESOLVED' ?

**Comment by rpj17-santec** [comment]
RESOLVED
